# Generated by Django 5.2.5 on 2025-08-18 19:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('icon', models.TextField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50000.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TENTATIVE', 'Tentative'), ('SIGNING', 'Signing'), ('DEFINITE', 'Definite'), ('CANCELLED', 'Cancelled')], default='TENTATIVE', max_length=10)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=70)),
                ('message', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('total_estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioapi.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('FOH_ENGINEER', 'FOH Engineer'), ('MONITOR_ENGINEER', 'Monitor Engineer'), ('PRODUCTION_MANAGER', 'Production Manager'), ('VIDEO_ENGINEER', 'Video Engineer'), ('LIGHTING_TECH', 'Lighting Technician'), ('AUDIO_TECH', 'Audio Technician')], max_length=50)),
                ('day_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('FULL_DAY', 'Full Day'), ('HALF_DAY', 'Half Day'), ('CUSTOM', 'Custom Rate')], default='FULL_DAY', max_length=20)),
                ('day_rate_at_booking', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custom_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('days_worked', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioapi.booking')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioapi.staff')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_staff',
            field=models.ManyToManyField(through='audioapi.BookingStaff', to='audioapi.staff'),
        ),
    ]
