# Generated by Django 5.2.2 on 2025-08-08 19:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50000.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TENTATIVE', 'Tentative'), ('SIGNING', 'Signing'), ('DEFINITE', 'Definite'), ('CANCELLED', 'Cancelled')], default='TENTATIVE', max_length=10)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=70)),
                ('message', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(null=True)),
                ('confirmed_at', models.DateField(auto_now_add=True)),
                ('confirmed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmedbyuser', to=settings.AUTH_USER_MODEL)),
                ('inquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiryid', to='audioapi.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='BookingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingstaff', to='audioapi.booking')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffbooking', to='audioapi.staff')),
            ],
        ),
    ]
